<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netframework3.5.0</TargetFramework>
        <AssemblyName>Bridge Project</AssemblyName>
        <Description>A Bridge to connect Orpheon and PonyIslandChallengesMod.</Description>
        <Version>1.0.0</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>Latest</LangVersion>
        <RootNamespace>Bridge_Project</RootNamespace>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>
    
    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
    </ItemGroup>
    
    <Target Name="PostBuild" AfterTargets="Build">
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="C:\Program Files (x86)\Steam\steamapps\common\Pony Island\BepInEx\plugins\Bridge" SkipUnchangedFiles="false" />
    </Target>
</Project>